import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'


const Home: NextPage = () => {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='w-full h-screen bg-[#202023] flex justify-center items-center space-x-24'>
        <Image src="/P.jpg" alt="" width={400} height={400} className="rounded-2xl"/>
        <div className='w-1/5 space-y-14'>
          <p className='text-white font-fontJapan font-bold text-4xl w-full text-center'>不要懷疑,小p好帥!</p>
          <div className='flex space-x-4'>
            <a href="/dashboard" className='bg-[#34343e] w-1/2 h-14 rounded-lg font-fontJapan font-bold text-[#D4D4D2] flex justify-center items-center hover:bg-[#191c1e] '>
              <p className=''>點我進入</p>
            </a>
            <a href="https://www.phalanity.com.tw" className='bg-[#F3D621] w-1/2 h-14 rounded-lg font-fontJapan font-bold text-[#202023] flex justify-center items-center hover:bg-[#FFDC35]'>
              <p className=''>官網</p>
            </a>
          </div>
          
        </div>
       
      </main>
    </div>
  )
}

export default Home
